###peticion get - todas los docentes
get http://localhost:8080/api/docentes

###peticion get - un solo docente
get http://localhost:8080/api/docentes/1

###peticion post - crear un docente
POST http://localhost:8080/api/docentes
Content-Type: application/json

{
    "nombre":"Juan Perez", 
    "grupo":"1A", 
    "tipoMateria":"Ingles"
}


###peticion put - para actualizar docente
PUT http://localhost:8080/api/docentes/18
Content-Type: application/json

{
    "nombre":"Daniela Guzman", 
    "grupo":"1C", 
    "tipoMateria":"Matematicas"
}

###peticion put - para eliminar Docente
DELETE http://localhost:8080/api/docentes/19
Content-Type: application/json

{
    "id":19
}

###peticion post - para login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email":"admin@ami.com", 
    "password":"admin123"
}

###peticion post - crear un usuario
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "email":"docente1@ami.com", 
    "password":"docente123",
    "rol":"seller"
}

# peticion para Obtener todas los estudiantes
GET http://localhost:8080/api/estudiantes

#obtener un estudiante por id
GET http://localhost:8080/api/estudiantes/1

# crear un estudiante
POST http://localhost:8080/api/estudiantes
Content-Type: application/json

{
    "nombre": "Luis Ramírez",
    "identificacion": "1032456789",
    "edad": 14,
    "grupo": "2B"
}

# actualizar un estudiante
PUT http://localhost:8080/api/estudiantes/5
Content-Type: application/json

{
    "nombre": "Laura Torres",
    "identificacion": "1032456888",
    "edad": 15,
    "grupo": "2C"
}

# eliminar un estudiante
DELETE http://localhost:8080/api/estudiantes/19
